name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/wpf-name.png
    - assets/page-1/images/bi-eye.png
    - assets/page-1/images/group.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/fluent-emoji-flat-hospital.png
    - assets/page-1/images/vector-cTZ.png
    - assets/page-1/images/wpf-name-fju.png
    - assets/page-1/images/group-200.png
    - assets/page-1/images/vector-x1M.png
    - assets/page-1/images/bi-arrow-down.png
    - assets/page-1/images/chevron.png
    - assets/page-1/images/vector-G3q.png
    - assets/page-1/images/vector-21d.png
    - assets/page-1/images/vector-wzP.png
    - assets/page-1/images/ri-pin-distance-fill.png
    - assets/page-1/images/wpf-name-ef9.png
    - assets/page-1/images/wpf-name-6RD.png
    - assets/page-1/images/ellipse-11.png
    - assets/page-1/images/vector-cA3.png
    - assets/page-1/images/group-200-Er3.png
    - assets/page-1/images/ellipse-12.png
    - assets/page-1/images/group-UrT.png
    - assets/page-1/images/vector-KR1.png
    - assets/page-1/images/bi-arrow-down-nC7.png
    - assets/page-1/images/vector-mpj.png
    - assets/page-1/images/vector-bWo.png
    - assets/page-1/images/vector-1MR.png
    - assets/page-1/images/bi-arrow-down-s8j.png
    - assets/page-1/images/ri-pin-distance-fill-FxT.png
    - assets/page-1/images/vector-eyu.png
    - assets/page-1/images/vector-X27.png
    - assets/page-1/images/ellipse-6.png
    - assets/page-1/images/group-RWo.png
    - assets/page-1/images/vector-LTy.png
    - assets/page-1/images/ellipse-8.png
    - assets/page-1/images/ic-baseline-call.png
    - assets/page-1/images/vector-nF1.png
    - assets/page-1/images/vector-B2F.png
    - assets/page-1/images/logo-1-1.png
    - assets/page-1/images/vector-u2o.png
    - assets/page-1/images/fluent-emoji-flat-hospital-GKH.png
    - assets/page-1/images/fluent-emoji-flat-hospital-AoH.png
    - assets/page-1/images/vector-wyh.png
    - assets/page-1/images/group-200-3Tm.png
    - assets/page-1/images/vector-LF9.png
    - assets/page-1/images/bi-eye-eWj.png
    - assets/page-1/images/vector-7wM.png
    - assets/page-1/images/backround-line.png
    - assets/page-1/images/ic-baseline-call-Gym.png
    - assets/page-1/images/group-b2P.png
    - assets/page-1/images/vector-tRu.png
    - assets/page-1/images/ellipse-10.png
    - assets/page-1/images/home-icon.png
    - assets/page-1/images/ri-pin-distance-fill-sEP.png
    - assets/page-1/images/vector-XBm.png
    - assets/page-1/images/ic-baseline-call-4zK.png
    - assets/page-1/images/ic-baseline-call-ks9.png
    - assets/page-1/images/logo-1-1-kw1.png
    - assets/page-1/images/ellipse-9.png
    - assets/page-1/images/bi-eye-CLF.png
    - assets/page-1/images/vector-XXV.png
    - assets/page-1/images/vector-rw1.png
    - assets/page-1/images/bi-arrow-down-73d.png
    - assets/page-1/images/ri-pin-distance-fill-Jxo.png
    - assets/page-1/images/group-200-yHR.png
    - assets/page-1/images/ellipse-9-MNf.png
    - assets/page-1/images/vector-Db5.png
    - assets/page-1/images/vector-BH1.png
    - assets/page-1/images/bi-arrow-down-2YF.png
    - assets/page-1/images/vector-N6s.png
    - assets/page-1/images/donar-search.png
    - assets/page-1/images/fluent-emoji-flat-hospital-cWj.png
    - assets/page-1/images/fluent-emoji-flat-hospital-RLj.png
    - assets/page-1/images/ellipse-9-E7Z.png
    - assets/page-1/images/group-200-rvs.png
    - assets/page-1/images/vector-dmq.png
    - assets/page-1/images/vector-YBH.png
    - assets/page-1/images/maki-cross.png
    - assets/page-1/images/vector-o1H.png
    - assets/page-1/images/material-symbols-search-rounded.png
    - assets/page-1/images/vector-wGT.png
    - assets/page-1/images/group-AJ3.png
    - assets/page-1/images/vector-Ui3.png
    - assets/page-1/images/fluent-emoji-flat-hospital-7uR.png
    - assets/page-1/images/vector-rkX.png
    - assets/page-1/images/ellipse-6-gis.png
    - assets/page-1/images/ic-baseline-call-TcT.png
    - assets/page-1/images/fluent-emoji-flat-hospital-axX.png
    - assets/page-1/images/vector-9Z1.png
    - assets/page-1/images/ic-baseline-call-6bH.png
    - assets/page-1/images/vector-k5V.png
    - assets/page-1/images/vector-7x3.png
    - assets/page-1/images/fluent-emoji-flat-hospital-sDR.png
    - assets/page-1/images/vector-BmR.png
    - assets/page-1/images/vector-kA3.png
    - assets/page-1/images/group-A8w.png
    - assets/page-1/images/vector-AEj.png
    - assets/page-1/images/ellipse-10-SCF.png
    - assets/page-1/images/vector-8jy.png
    - assets/page-1/images/waves.png
    - assets/page-1/images/ri-pin-distance-fill-h11.png
    - assets/page-1/images/vector-tzK.png
    - assets/page-1/images/vector-MYB.png
    - assets/page-1/images/backround-line-GdV.png
    - assets/page-1/images/vector-zjq.png
    - assets/page-1/images/maki-cross-6wH.png
    - assets/page-1/images/vector-XY3.png
    - assets/page-1/images/splash-screen.png
    - assets/page-1/images/group-nko.png
    - assets/page-1/images/group-200-kQ7.png
    - assets/page-1/images/vector-SvT.png
    - assets/page-1/images/group-Lkw.png
    - assets/page-1/images/vector-Co9.png
    - assets/page-1/images/wpf-name-TTm.png
    - assets/page-1/images/ic-baseline-call-sLB.png
    - assets/page-1/images/ellipse-8-NRM.png
    - assets/page-1/images/ri-pin-distance-fill-ffM.png
    - assets/page-1/images/vector-5RZ.png
    - assets/page-1/images/maki-cross-su9.png
    - assets/page-1/images/vector-d7d.png
    - assets/page-1/images/vector-c3R.png
    - assets/page-1/images/vector-N8P.png
    - assets/page-1/images/group-XX5.png
    - assets/page-1/images/vector-rpo.png
    - assets/page-1/images/ic-baseline-call-Cp7.png
    - assets/page-1/images/vector-Ysy.png
    - assets/page-1/images/group-200-rym.png
    - assets/page-1/images/ic-baseline-call-DZR.png
    - assets/page-1/images/ri-pin-distance-fill-yoV.png
    - assets/page-1/images/wpf-name-RAo.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/ic-baseline-call-vK9.png
    - assets/page-1/images/image-2-4AT.png
    - assets/page-1/images/vector-nKH.png
    - assets/page-1/images/ri-pin-distance-fill-qcs.png
    - assets/page-1/images/vector-zVm.png
    - assets/page-1/images/ellipse-8-KD1.png
    - assets/page-1/images/vector-ckP.png
    - assets/page-1/images/wpf-name-dJ7.png
    - assets/page-1/images/group-200-h6w.png
    - assets/page-1/images/vector-6t7.png
    - assets/page-1/images/wpf-name-om9.png
    - assets/page-1/images/waves-H1y.png
    - assets/page-1/images/group-225.png
    - assets/page-1/images/wpf-name-Heo.png
    - assets/page-1/images/vector-hdh.png
    - assets/page-1/images/vector-nuM.png
    - assets/page-1/images/vector-S8f.png
    - assets/page-1/images/vector-BEf.png
    - assets/page-1/images/vector-SCX.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/vector-zkP.png
    - assets/page-1/images/fluent-emoji-flat-hospital-MDZ.png
    - assets/page-1/images/ic-baseline-call-HmR.png
    - assets/page-1/images/group-200-aP9.png
    - assets/page-1/images/fluent-emoji-flat-hospital-PYs.png
    - assets/page-1/images/vector-vj9.png
    - assets/page-1/images/group-d7m.png
    - assets/page-1/images/vector-4w9.png
    - assets/page-1/images/vector-ao1.png
    - assets/page-1/images/ri-pin-distance-fill-iXq.png
    - assets/page-1/images/group-5UB.png
    - assets/page-1/images/ri-pin-distance-fill-7r7.png
    - assets/page-1/images/vector-bHR.png
    - assets/page-1/images/home-icon-YEb.png
    - assets/page-1/images/group-200-48F.png
    - assets/page-1/images/vector-vxF.png
    - assets/page-1/images/group-200-ssV.png
    - assets/page-1/images/vector-hbd.png
    - assets/page-1/images/ic-baseline-call-s6X.png
    - assets/page-1/images/vector-n71.png
    - assets/page-1/images/ic-baseline-call-pZV.png
    - assets/page-1/images/vector-m6X.png
    - assets/page-1/images/ellipse-1-6eb.png
    - assets/page-1/images/vector-CcP.png
    - assets/page-1/images/vector-5i7.png
    - assets/page-1/images/group-t9m.png
    - assets/page-1/images/home-icon-FFD.png
    - assets/page-1/images/group-R9h.png
    - assets/page-1/images/ellipse-9-Bo5.png
    - assets/page-1/images/wpf-name-kLP.png
    - assets/page-1/images/wpf-name-4M5.png
    - assets/page-1/images/vector-pr3.png
    - assets/page-1/images/vector-Pu9.png
    - assets/page-1/images/group-200-xhM.png
    - assets/page-1/images/vector-vu5.png
    - assets/page-1/images/group-200-qWF.png
    - assets/page-1/images/wpf-name-QZM.png
    - assets/page-1/images/vector-P1y.png
    - assets/page-1/images/ri-pin-distance-fill-uEF.png
    - assets/page-1/images/group-200-Sjy.png
    - assets/page-1/images/group-200-8Mu.png
    - assets/page-1/images/ellipse-8-tby.png
    - assets/page-1/images/wpf-name-4m5.png
    - assets/page-1/images/wpf-name-UTR.png
    - assets/page-1/images/donar-search-ESb.png
    - assets/page-1/images/vector-C8X.png
    - assets/page-1/images/vector-mBd.png
    - assets/page-1/images/vector-b5R.png
    - assets/page-1/images/ri-pin-distance-fill-tyd.png
    - assets/page-1/images/ellipse-1-9Rh.png
    - assets/page-1/images/ellipse-1-HCT.png
    - assets/page-1/images/group-oY3.png
    - assets/page-1/images/ri-pin-distance-fill-ecX.png
    - assets/page-1/images/group-252.png
    - assets/page-1/images/clarity-notification-outline-badged.png
    - assets/page-1/images/vector-Vw5.png
    - assets/page-1/images/group-249.png
    - assets/page-1/images/vector-KFD.png
    - assets/page-1/images/vector-Ztb.png
    - assets/page-1/images/group-254.png
    - assets/page-1/images/ri-pin-distance-fill-PC3.png
    - assets/page-1/images/vector-S6j.png
    - assets/page-1/images/ic-baseline-call-FFm.png
    - assets/page-1/images/group-FSF.png
    - assets/page-1/images/group-249-kQw.png
    - assets/page-1/images/group-250.png
    - assets/page-1/images/madmax-2.png
    - assets/page-1/images/vector-XoM.png
    - assets/page-1/images/group-253.png
    - assets/page-1/images/donar-search-j8j.png
    - assets/page-1/images/vector-t1d.png
    - assets/page-1/images/vector-39R.png
    - assets/page-1/images/vector-byZ.png
    - assets/page-1/images/home-icon-Y87.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/logo-1-1-bg.png
    - assets/page-1/images/vector-PhH.png
    - assets/page-1/images/logo-1-1-bg-dhR.png
    - assets/page-1/images/vector-hts.png
    - assets/page-1/images/clarity-notification-outline-badged-7d9.png
    - assets/page-1/images/down-arrow.png
    - assets/page-1/images/vector-EBy.png
    - assets/page-1/images/vector-zgw.png
    - assets/page-1/images/wpf-name-MnP.png
    - assets/page-1/images/ri-pin-distance-fill-isq.png
    - assets/page-1/images/ic-baseline-call-Ca3.png
    - assets/page-1/images/donar-search-A15.png
    - assets/page-1/images/donar-search-95H.png
    - assets/page-1/images/simple-photocentric-music-mix-youtube-thumbnail-1-2.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-2.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-2-XCB.png
    - assets/page-1/images/group-251.png
    - assets/page-1/images/down-arrow-Rbd.png
    - assets/page-1/images/image-22-VfV.png
    - assets/page-1/images/home-icon-KJw.png
    - assets/page-1/images/vector-mWP.png
    - assets/page-1/images/blood-drop.png
    - assets/page-1/images/blood-drop-kUF.png
    - assets/page-1/images/home-icon-1U3.png
    - assets/page-1/images/blood-drop-zdu.png
    - assets/page-1/images/blood-drop-2Fh.png
    - assets/page-1/images/blood-drop-w3D.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-1-2.png
    - assets/page-1/images/simple-photocentric-music-mix-youtube-thumbnail-1-2-cLo.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-1-2-9cs.png
    - assets/page-1/images/vector-Tbm.png
    - assets/page-1/images/blood-drop-6nj.png
    - assets/page-1/images/vector-tLw.png
    - assets/page-1/images/blood-drop-5kB.png
    - assets/page-1/images/madmax-2-aCo.png
    - assets/page-1/images/vector-8rj.png
    - assets/page-1/images/blood-drop-jzf.png
    - assets/page-1/images/vector-XB5.png
    - assets/page-1/images/vector-LGw.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-1-2-CbH.png
    - assets/page-1/images/group-249-Tfd.png
    - assets/page-1/images/donar-search-vCo.png
    - assets/page-1/images/logo-1-1-bg-h2X.png
    - assets/page-1/images/simple-photocentric-music-mix-youtube-thumbnail-1-2-1KD.png
    - assets/page-1/images/clarity-notification-outline-badged-LwZ.png
    - assets/page-1/images/group-249-oQB.png
    - assets/page-1/images/blood-transfusion.png
    - assets/page-1/images/donar-search-ECw.png
    - assets/page-1/images/hospital.png
    - assets/page-1/images/vector-pRV.png
    - assets/page-1/images/clarity-notification-outline-badged-3cj.png
    - assets/page-1/images/vector-EsZ.png
    - assets/page-1/images/donar-search-wMq.png
    - assets/page-1/images/logo-1-1-bg-uZq.png
    - assets/page-1/images/ellipse-8-G7R.png
    - assets/page-1/images/home-icon-kMM.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-2-Eq5.png
    - assets/page-1/images/madmax-2-8Hm.png
    - assets/page-1/images/home-icon-V27.png
    - assets/page-1/images/blood-drop-JuD.png
    - assets/page-1/images/group-249-yVH.png
    - assets/page-1/images/rectangle-107.png
    - assets/page-1/images/ellipse-9-78K.png
    - assets/page-1/images/chevron-JE3.png
    - assets/page-1/images/image-22-UBR.png
    - assets/page-1/images/group-MpK.png
    - assets/page-1/images/vector-4bR.png
    - assets/page-1/images/chevron-KhR.png
    - assets/page-1/images/uiw-date.png
    - assets/page-1/images/vector-RYK.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
