name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/group-200.png
    - assets/page-1/images/bi-eye.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/vector-61m.png
    - assets/page-1/images/ellipse-11.png
    - assets/page-1/images/bi-arrow-down.png
    - assets/page-1/images/splash-screen.png
    - assets/page-1/images/ellipse-12.png
    - assets/page-1/images/ellipse-8.png
    - assets/page-1/images/bi-arrow-down-G7h.png
    - assets/page-1/images/material-symbols-search-rounded.png
    - assets/page-1/images/group.png
    - assets/page-1/images/bi-arrow-down-ZtT.png
    - assets/page-1/images/ri-pin-distance-fill.png
    - assets/page-1/images/vector-WqD.png
    - assets/page-1/images/fluent-emoji-flat-hospital.png
    - assets/page-1/images/group-XN7.png
    - assets/page-1/images/backround-line.png
    - assets/page-1/images/vector-Ru9.png
    - assets/page-1/images/ellipse-6.png
    - assets/page-1/images/ic-baseline-call.png
    - assets/page-1/images/group-200-BN7.png
    - assets/page-1/images/ellipse-10.png
    - assets/page-1/images/wpf-name.png
    - assets/page-1/images/vector-9pK.png
    - assets/page-1/images/group-200-TrF.png
    - assets/page-1/images/bi-eye-XcK.png
    - assets/page-1/images/bi-arrow-down-SzB.png
    - assets/page-1/images/vector-vFh.png
    - assets/page-1/images/group-yfD.png
    - assets/page-1/images/bi-arrow-down-MZH.png
    - assets/page-1/images/fluent-emoji-flat-hospital-BDR.png
    - assets/page-1/images/vector-4to.png
    - assets/page-1/images/ellipse-8-UqM.png
    - assets/page-1/images/vector-zVu.png
    - assets/page-1/images/fluent-emoji-flat-hospital-XzF.png
    - assets/page-1/images/vector-otT.png
    - assets/page-1/images/wpf-name-hrf.png
    - assets/page-1/images/ri-pin-distance-fill-CSj.png
    - assets/page-1/images/vector-Ruh.png
    - assets/page-1/images/vector-6Xy.png
    - assets/page-1/images/fluent-emoji-flat-hospital-T9h.png
    - assets/page-1/images/vector-Czs.png
    - assets/page-1/images/vector-qrF.png
    - assets/page-1/images/vector-bqR.png
    - assets/page-1/images/home-icon.png
    - assets/page-1/images/vector-mBM.png
    - assets/page-1/images/ri-pin-distance-fill-aLP.png
    - assets/page-1/images/ellipse-9.png
    - assets/page-1/images/vector-vBZ.png
    - assets/page-1/images/ic-baseline-call-66j.png
    - assets/page-1/images/vector-hLb.png
    - assets/page-1/images/wpf-name-V8s.png
    - assets/page-1/images/ellipse-9-Q2B.png
    - assets/page-1/images/vector-551.png
    - assets/page-1/images/vector-ccX.png
    - assets/page-1/images/ri-pin-distance-fill-XGj.png
    - assets/page-1/images/vector-Ve7.png
    - assets/page-1/images/vector-CTH.png
    - assets/page-1/images/bi-eye-VxB.png
    - assets/page-1/images/vector-NJT.png
    - assets/page-1/images/ic-baseline-call-nYX.png
    - assets/page-1/images/vector-Nf9.png
    - assets/page-1/images/vector-aCo.png
    - assets/page-1/images/group-200-y5q.png
    - assets/page-1/images/vector-GMV.png
    - assets/page-1/images/group-X9Z.png
    - assets/page-1/images/vector-iNK.png
    - assets/page-1/images/vector-q9y.png
    - assets/page-1/images/vector-Mmq.png
    - assets/page-1/images/vector-qKd.png
    - assets/page-1/images/fluent-emoji-flat-hospital-pDV.png
    - assets/page-1/images/vector-agP.png
    - assets/page-1/images/fluent-emoji-flat-hospital-AEj.png
    - assets/page-1/images/donar-search.png
    - assets/page-1/images/group-200-hFu.png
    - assets/page-1/images/vector-WYf.png
    - assets/page-1/images/vector-JUX.png
    - assets/page-1/images/vector-YTZ.png
    - assets/page-1/images/group-VPm.png
    - assets/page-1/images/wpf-name-KMq.png
    - assets/page-1/images/vector-RSw.png
    - assets/page-1/images/vector-Fnf.png
    - assets/page-1/images/backround-line-rE3.png
    - assets/page-1/images/vector-84P.png
    - assets/page-1/images/ic-baseline-call-1dy.png
    - assets/page-1/images/ic-baseline-call-44P.png
    - assets/page-1/images/vector-aZd.png
    - assets/page-1/images/ri-pin-distance-fill-BYT.png
    - assets/page-1/images/logo-1-1.png
    - assets/page-1/images/wpf-name-pyM.png
    - assets/page-1/images/vector-noh.png
    - assets/page-1/images/vector-bM9.png
    - assets/page-1/images/logo-1-1-vw9.png
    - assets/page-1/images/group-eG7.png
    - assets/page-1/images/wpf-name-VKu.png
    - assets/page-1/images/group-200-3Bd.png
    - assets/page-1/images/ri-pin-distance-fill-4sR.png
    - assets/page-1/images/vector-JhD.png
    - assets/page-1/images/group-200-FeP.png
    - assets/page-1/images/vector-eXR.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/ellipse-9-Nym.png
    - assets/page-1/images/vector-Qum.png
    - assets/page-1/images/vector-Cdm.png
    - assets/page-1/images/vector-fmR.png
    - assets/page-1/images/ri-pin-distance-fill-zoh.png
    - assets/page-1/images/vector-YcF.png
    - assets/page-1/images/group-VSo.png
    - assets/page-1/images/ellipse-6-zJK.png
    - assets/page-1/images/vector-dE7.png
    - assets/page-1/images/vector-BJf.png
    - assets/page-1/images/wpf-name-g8o.png
    - assets/page-1/images/ellipse-8-iHd.png
    - assets/page-1/images/chevron.png
    - assets/page-1/images/vector-ktF.png
    - assets/page-1/images/fluent-emoji-flat-hospital-nby.png
    - assets/page-1/images/vector-sxB.png
    - assets/page-1/images/vector-G1D.png
    - assets/page-1/images/waves.png
    - assets/page-1/images/vector-4SB.png
    - assets/page-1/images/vector-HcK.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/vector-UeB.png
    - assets/page-1/images/fluent-emoji-flat-hospital-rQw.png
    - assets/page-1/images/ri-pin-distance-fill-Te7.png
    - assets/page-1/images/waves-sNw.png
    - assets/page-1/images/wpf-name-ZAP.png
    - assets/page-1/images/ellipse-1-vBH.png
    - assets/page-1/images/maki-cross.png
    - assets/page-1/images/ellipse-10-Z6X.png
    - assets/page-1/images/vector-2oy.png
    - assets/page-1/images/vector-cWb.png
    - assets/page-1/images/ellipse-1-Vq9.png
    - assets/page-1/images/ri-pin-distance-fill-jL3.png
    - assets/page-1/images/ic-baseline-call-pnj.png
    - assets/page-1/images/ic-baseline-call-oJX.png
    - assets/page-1/images/group-200-FvX.png
    - assets/page-1/images/vector-5gb.png
    - assets/page-1/images/vector-LXH.png
    - assets/page-1/images/group-200-opj.png
    - assets/page-1/images/vector-cuM.png
    - assets/page-1/images/wpf-name-LBh.png
    - assets/page-1/images/maki-cross-YJs.png
    - assets/page-1/images/vector-bXM.png
    - assets/page-1/images/group-D9y.png
    - assets/page-1/images/group-bbd.png
    - assets/page-1/images/group-DN7.png
    - assets/page-1/images/group-200-L5M.png
    - assets/page-1/images/vector-DPM.png
    - assets/page-1/images/group-200-26K.png
    - assets/page-1/images/ic-baseline-call-b4B.png
    - assets/page-1/images/wpf-name-EC7.png
    - assets/page-1/images/ic-baseline-call-YPh.png
    - assets/page-1/images/vector-tto.png
    - assets/page-1/images/vector-s7m.png
    - assets/page-1/images/ri-pin-distance-fill-r6j.png
    - assets/page-1/images/vector-LYw.png
    - assets/page-1/images/fluent-emoji-flat-hospital-ZkK.png
    - assets/page-1/images/donar-search-Usq.png
    - assets/page-1/images/group-200-U55.png
    - assets/page-1/images/vector-uiX.png
    - assets/page-1/images/vector-fXu.png
    - assets/page-1/images/wpf-name-Vhq.png
    - assets/page-1/images/vector-EYw.png
    - assets/page-1/images/image-2-hLj.png
    - assets/page-1/images/vector-551-ZVy.png
    - assets/page-1/images/vector-B7M.png
    - assets/page-1/images/group-91R.png
    - assets/page-1/images/vector-tjh.png
    - assets/page-1/images/group-rwR.png
    - assets/page-1/images/vector-wT5.png
    - assets/page-1/images/ri-pin-distance-fill-jJP.png
    - assets/page-1/images/wpf-name-EZu.png
    - assets/page-1/images/ri-pin-distance-fill-ePH.png
    - assets/page-1/images/wpf-name-49u.png
    - assets/page-1/images/vector-PiP.png
    - assets/page-1/images/wpf-name-qPM.png
    - assets/page-1/images/ellipse-1-6Vd.png
    - assets/page-1/images/vector-J1M.png
    - assets/page-1/images/vector-fEX.png
    - assets/page-1/images/group-200-BZH.png
    - assets/page-1/images/maki-cross-VeP.png
    - assets/page-1/images/ri-pin-distance-fill-79y.png
    - assets/page-1/images/group-200-5Nw.png
    - assets/page-1/images/vector-EFq.png
    - assets/page-1/images/donar-search-AvB.png
    - assets/page-1/images/ic-baseline-call-dqh.png
    - assets/page-1/images/clarity-notification-outline-badged.png
    - assets/page-1/images/ic-baseline-call-yyR.png
    - assets/page-1/images/ic-baseline-call-VUT.png
    - assets/page-1/images/fluent-emoji-flat-hospital-iBy.png
    - assets/page-1/images/vector-8dD.png
    - assets/page-1/images/vector-gUo.png
    - assets/page-1/images/vector-XTD.png
    - assets/page-1/images/vector-g5D.png
    - assets/page-1/images/vector-RSX.png
    - assets/page-1/images/group-200-Biw.png
    - assets/page-1/images/vector-goR.png
    - assets/page-1/images/group-Dou.png
    - assets/page-1/images/down-arrow.png
    - assets/page-1/images/ellipse-9-LDd.png
    - assets/page-1/images/vector-nb9.png
    - assets/page-1/images/ellipse-8-Lcf.png
    - assets/page-1/images/ic-baseline-call-VEo.png
    - assets/page-1/images/vector-pk7.png
    - assets/page-1/images/wpf-name-AJj.png
    - assets/page-1/images/group-WGf.png
    - assets/page-1/images/vector-34s.png
    - assets/page-1/images/home-icon-UgX.png
    - assets/page-1/images/ic-baseline-call-F83.png
    - assets/page-1/images/ic-baseline-call-arT.png
    - assets/page-1/images/ri-pin-distance-fill-Jf9.png
    - assets/page-1/images/vector-vby.png
    - assets/page-1/images/ri-pin-distance-fill-YqM.png
    - assets/page-1/images/group-225.png
    - assets/page-1/images/vector-3FV.png
    - assets/page-1/images/vector-hPM.png
    - assets/page-1/images/group-251.png
    - assets/page-1/images/group-rYX.png
    - assets/page-1/images/vector-HxT.png
    - assets/page-1/images/group-249.png
    - assets/page-1/images/down-arrow-X8K.png
    - assets/page-1/images/group-252.png
    - assets/page-1/images/vector-9M9.png
    - assets/page-1/images/home-icon-4mm.png
    - assets/page-1/images/vector-3bD.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-1-2.png
    - assets/page-1/images/vector-iHm.png
    - assets/page-1/images/group-250.png
    - assets/page-1/images/group-249-pRu.png
    - assets/page-1/images/donar-search-QGX.png
    - assets/page-1/images/vector-Mkj.png
    - assets/page-1/images/donar-search-7nF.png
    - assets/page-1/images/donar-search-45m.png
    - assets/page-1/images/home-icon-G2b.png
    - assets/page-1/images/logo-1-1-bg.png
    - assets/page-1/images/vector-Wxw.png
    - assets/page-1/images/group-253.png
    - assets/page-1/images/donar-search-VEX.png
    - assets/page-1/images/home-icon-YnB.png
    - assets/page-1/images/vector-rgP.png
    - assets/page-1/images/vector-q2o.png
    - assets/page-1/images/logo-1-1-bg-LF1.png
    - assets/page-1/images/clarity-notification-outline-badged-epP.png
    - assets/page-1/images/logo-1-1-bg-uCT.png
    - assets/page-1/images/group-249-wmq.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-1-2-9o5.png
    - assets/page-1/images/home-icon-aMd.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-1-2-Pbu.png
    - assets/page-1/images/donar-search-wNX.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/image-22-GNb.png
    - assets/page-1/images/vector-uAP.png
    - assets/page-1/images/vector-ybu.png
    - assets/page-1/images/vector-t6s.png
    - assets/page-1/images/blood-drop.png
    - assets/page-1/images/blood-drop-7Tu.png
    - assets/page-1/images/blood-drop-sNX.png
    - assets/page-1/images/blood-drop-61d.png
    - assets/page-1/images/madmax-2.png
    - assets/page-1/images/blood-drop-wro.png
    - assets/page-1/images/blood-drop-J8w.png
    - assets/page-1/images/blood-drop-xVd.png
    - assets/page-1/images/clarity-notification-outline-badged-VXM.png
    - assets/page-1/images/image-22-b4T.png
    - assets/page-1/images/simple-photocentric-music-mix-youtube-thumbnail-1-2.png
    - assets/page-1/images/blood-drop-ogs.png
    - assets/page-1/images/simple-photocentric-music-mix-youtube-thumbnail-1-2-HK5.png
    - assets/page-1/images/chevron-iKq.png
    - assets/page-1/images/vector-aXq.png
    - assets/page-1/images/simple-photocentric-music-mix-youtube-thumbnail-1-2-TMh.png
    - assets/page-1/images/home-icon-QGw.png
    - assets/page-1/images/madmax-2-5FD.png
    - assets/page-1/images/madmax-2-Jwq.png
    - assets/page-1/images/blood-drop-3JF.png
    - assets/page-1/images/clarity-notification-outline-badged-MkB.png
    - assets/page-1/images/home-icon-hzF.png
    - assets/page-1/images/logo-1-1-bg-6XZ.png
    - assets/page-1/images/uiw-date.png
    - assets/page-1/images/group-249-wbD.png
    - assets/page-1/images/chevron-4iK.png
    - assets/page-1/images/group-254.png
    - assets/page-1/images/vector-855.png
    - assets/page-1/images/ellipse-9-DXM.png
    - assets/page-1/images/ellipse-8-yZZ.png
    - assets/page-1/images/group-vGw.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-2.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-2-UdM.png
    - assets/page-1/images/hospital.png
    - assets/page-1/images/vector-mB5.png
    - assets/page-1/images/the-measure-of-life-is-not-its-duration-but-its-donationt-2-1g3.png
    - assets/page-1/images/blood-transfusion.png
    - assets/page-1/images/vector-tH5.png
    - assets/page-1/images/rectangle-107.png
    - assets/page-1/images/group-249-G1D.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
